spring:
  profiles:
    active: local
  datasource:
    url: ${spring.datasource.url}
    username: root
    password: ${spring.datasource.password}
    hikari:
      connectionTimeout: 20000
  security:
    filter:
      order: 10
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

jwt:
  secret: mvY&IQwYVCUoPF3JcxoNpi0yhq04ryW!a#MUWCY4m8tr1%99sjJcxoNpi0yhq04ryW!a

